[project]
name = "choir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "harmonypy>=0.0.10",
    "igraph>=0.11.9",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "leidenalg>=0.10.2",
    "scanpy>=1.11.2",
]
